{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sendent-msteams.fullname" . }}-secret
  labels:
    {{- include "sendent-msteams.labels" . | nindent 4 }}
type: Opaque
data:
  MSAPP_PASSWORD: {{ required "secret.MSAPP_PASSWORD is required when secret.existingSecret is not set" .Values.secret.MSAPP_PASSWORD | b64enc | quote }}
{{- end }}